### PR TITLE
Add some code verification tests to the programmatic DynamoDB module

### PR DESCRIPTION
**Pull request by amcp**
This change adds some tests to the DynamoDB module, demonstrates testing with DynamoDB local and Gradle, and fixes some null pointer exceptions in DynamoDBProgrammaticKeyValue related to the fact that the encapsulated KeyValue was not delegated to for writeOnce, writeBulk, readOnce, and readBulk

### CODE REVIEW

**Comment by amcp** [comment]
@ipapapa this is what we discussed earlier today.

**Comment by ipapapa** [comment]
The build is failing. Would you like to check that?

**Comment by ipapapa** [comment]
@amcp Now that the other PR has been merged, would you like to move forward with this one as well?

**Comment by amcp** [comment]
@ipapapa @vinaykumarchella i am good to move forward now.

**Pull request merged**
